import os, sys, json, yaml, re, glob, random
from pathlib import Path

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

CONFIG_PATH = "config/teacher_config.yaml"
PROMPTS_PATH = "prompts/distill_prompts.yaml"
KB_DIRS = ["knowledge_base", "data/output", "data/input", "data/src", "docs"]
SKIP_EXTS = {
    ".gz",
    ".zip",
    ".png",
    ".jpg",
    ".jpeg",
    ".gif",
    ".pdf",
    ".d64",
    ".g64",
    ".prg",
    ".bin",
}


# ============================================================
# Teacher Backend Interface
# ============================================================
class TeacherBackend:
    def generate(self, system: str, user: str) -> str:
        raise NotImplementedError


class OpenCodeTeacher(TeacherBackend):
    def generate(self, system: str, user: str) -> str:
        print("[Teacher] OpenCode mode: dataset will be generated by the assistant.")
        print(
            "[Teacher] Run 'python pipeline/knowledge_distiller.py --generate' to signal the assistant."
        )
        return ""


class OpenRouterTeacher(TeacherBackend):
    def __init__(self, config):
        self.api_key = os.getenv("TEACHER_API_KEY", config.get("api_key", ""))
        self.model = config.get("model", "qwen/qwen3-32b")
        self.base_url = config.get("api_base", "https://openrouter.ai/api/v1")

    def generate(self, system: str, user: str) -> str:
        import requests

        resp = requests.post(
            f"{self.base_url}/chat/completions",
            headers={
                "Authorization": f"Bearer {self.api_key}",
                "Content-Type": "application/json",
            },
            json={
                "model": self.model,
                "messages": [
                    {"role": "system", "content": system},
                    {"role": "user", "content": user},
                ],
                "temperature": 0.3,
                "max_tokens": 2048,
            },
            timeout=120,
        )
        resp.raise_for_status()
        return resp.json()["choices"][0]["message"]["content"]


class GroqTeacher(TeacherBackend):
    def __init__(self, config):
        self.api_key = os.getenv("TEACHER_API_KEY", config.get("api_key", ""))
        self.model = config.get("model", "llama3-70b-8192")

    def generate(self, system: str, user: str) -> str:
        import requests

        resp = requests.post(
            "https://api.groq.com/openai/v1/chat/completions",
            headers={
                "Authorization": f"Bearer {self.api_key}",
                "Content-Type": "application/json",
            },
            json={
                "model": self.model,
                "messages": [
                    {"role": "system", "content": system},
                    {"role": "user", "content": user},
                ],
                "temperature": 0.3,
                "max_tokens": 2048,
            },
            timeout=120,
        )
        resp.raise_for_status()
        return resp.json()["choices"][0]["message"]["content"]


class OllamaTeacher(TeacherBackend):
    def __init__(self, config):
        self.model = config.get("model", "qwen3:32b")
        self.base_url = config.get("api_base", "http://localhost:11434")

    def generate(self, system: str, user: str) -> str:
        import requests

        resp = requests.post(
            f"{self.base_url}/api/chat",
            json={
                "model": self.model,
                "messages": [
                    {"role": "system", "content": system},
                    {"role": "user", "content": user},
                ],
                "options": {"temperature": 0.3},
            },
            timeout=300,
        )
        resp.raise_for_status()
        return resp.json()["message"]["content"]


class HuggingFaceTeacher(TeacherBackend):
    def __init__(self, config):
        self.api_key = os.getenv("TEACHER_API_KEY", config.get("api_key", ""))
        self.model = config.get("model", "Qwen/Qwen3-32B-Instruct")

    def generate(self, system: str, user: str) -> str:
        import requests

        headers = {"Authorization": f"Bearer {self.api_key}"}
        payload = {
            "inputs": f"<|im_start|>system\n{system}<|im_end|>\n<|im_start|>user\n{user}<|im_end|>\n<|im_start|>assistant\n",
            "parameters": {"max_new_tokens": 2048, "temperature": 0.3},
        }
        resp = requests.post(
            f"https://api-inference.huggingface.co/models/{self.model}",
            headers=headers,
            json=payload,
            timeout=120,
        )
        resp.raise_for_status()
        return resp.json()[0]["generated_text"]


# ============================================================
# Teacher Factory
# ============================================================
BACKENDS = {
    "opencode": OpenCodeTeacher,
    "openrouter": OpenRouterTeacher,
    "groq": GroqTeacher,
    "ollama": OllamaTeacher,
    "huggingface": HuggingFaceTeacher,
}


def create_teacher(config: dict) -> TeacherBackend:
    backend_type = config.get("teacher", {}).get("type", "opencode")
    cls = BACKENDS.get(backend_type)
    if not cls:
        raise ValueError(
            f"Unknown teacher backend: {backend_type}. Options: {list(BACKENDS.keys())}"
        )
    return cls(config.get("teacher", {}))


# ============================================================
# Chunk Loader
# ============================================================
def load_chunks(kb_dirs=None, max_chunks=0):
    kb_dirs = kb_dirs or KB_DIRS
    chunks = []
    src_map = {}

    for kb_dir in kb_dirs:
        if not os.path.isdir(kb_dir):
            continue
        for fpath in glob.glob(f"{kb_dir}/**/*.*", recursive=True):
            ext = os.path.splitext(fpath)[1].lower()
            if ext in SKIP_EXTS or "vectorstore" in fpath:
                continue
            try:
                with open(fpath, "r", encoding="utf-8", errors="replace") as f:
                    text = f.read().strip()
                if not text or len(text) < 100:
                    continue
            except Exception:
                continue

            lines = text.split("\n")
            for i in range(0, len(lines), 60):
                chunk_text = "\n".join(lines[i : i + 60])
                if len(chunk_text.strip()) < 80:
                    continue
                c = {
                    "id": f"{fpath}#L{i + 1}",
                    "source": fpath,
                    "text": chunk_text[:3000],
                }
                chunks.append(c)
                src_map[fpath] = src_map.get(fpath, 0) + 1

    if max_chunks > 0:
        random.shuffle(chunks)
        chunks = chunks[:max_chunks]

    return chunks


# ============================================================
# Distiller Engine
# ============================================================
class KnowledgeDistiller:
    def __init__(self, config_path=CONFIG_PATH, prompts_path=PROMPTS_PATH):
        with open(config_path) as f:
            self.config = yaml.safe_load(f)
        with open(prompts_path) as f:
            self.prompts = yaml.safe_load(f)
        self.teacher = create_teacher(self.config)
        self.strategy = self.config.get("teacher", {}).get("strategy", {})
        self.lang_order = self.strategy.get("languages", ["it", "en"])
        self.qa_per_chunk = self.strategy.get("qa_per_chunk", 2)

    def generate_all(self, chunks):
        dataset = []
        types = self.strategy.get(
            "types", ["factual", "code", "explain", "bugfix", "theory"]
        )
        total = len(chunks)

        for idx, chunk in enumerate(chunks):
            if idx % 10 == 0:
                print(
                    f"[Distiller] {idx}/{total} chunks processed ({len(dataset)} pairs so far)"
                )

            for chunk_type in types:
                prompt_cfg = self.prompts.get(chunk_type)
                if not prompt_cfg:
                    continue

                for lang in self.lang_order:
                    count = max(1, self.qa_per_chunk // len(self.lang_order))
                    user_msg = prompt_cfg["user_template"].format(
                        chunk=chunk["text"], count=count, language=lang
                    )
                    system_prompt = prompt_cfg["system"]

                    try:
                        raw = self.teacher.generate(system_prompt, user_msg)
                        parsed = self._parse_json(raw)
                        for item in parsed:
                            item["source"] = chunk["source"]
                            item["type"] = chunk_type
                            item["lang"] = lang
                            dataset.append(item)
                    except Exception as e:
                        print(f"  [WARN] Chunk {chunk['id']} type={chunk_type}: {e}")
                        continue

        return dataset

    def _parse_json(self, text):
        text = text.strip()
        text = re.sub(r"^```(?:json)?\s*", "", text)
        text = re.sub(r"\s*```$", "", text)
        return json.loads(text)

    def generate_dataset_file(self, chunks, output_path):
        dataset = self.generate_all(chunks)
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            for entry in dataset:
                f.write(json.dumps(entry, ensure_ascii=False) + "\n")
        print(f"[Distiller] Dataset salvato: {output_path} ({len(dataset)} entries)")
        return dataset

    def save_placeholder(self, output_path):
        dataset = [
            {
                "instruction": "Quale registro VIC-II controlla il colore del bordo?",
                "output": "Il registro $D020 del VIC-II controlla il colore del bordo del C64.",
                "source": "knowledge_base/c64_memory_map.md",
                "type": "factual",
                "lang": "it",
            }
        ]
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            for entry in dataset:
                f.write(json.dumps(entry, ensure_ascii=False) + "\n")
        print(f"[Distiller] Placeholder salvato in {output_path}")


# ============================================================
# CLI
# ============================================================
def main():
    import argparse

    parser = argparse.ArgumentParser(description="C64 Knowledge Distillation Pipeline")
    parser.add_argument(
        "--generate",
        action="store_true",
        help="Segnala all'assistente di generare il dataset",
    )
    parser.add_argument(
        "--teacher",
        type=str,
        default=None,
        help="Backend Teacher (opencode, openrouter, groq, ...)",
    )
    parser.add_argument("--model", type=str, default=None, help="Modello Teacher")
    parser.add_argument(
        "--max-chunks", type=int, default=0, help="Max chunks da processare"
    )
    parser.add_argument(
        "--output",
        type=str,
        default="data/output/distill_dataset.jsonl",
        help="File output dataset",
    )
    parser.add_argument(
        "--placeholder", action="store_true", help="Genera solo un placeholder"
    )

    args = parser.parse_args()

    config = yaml.safe_load(open(CONFIG_PATH))
    if args.teacher:
        config["teacher"]["type"] = args.teacher
    if args.model:
        config["teacher"]["model"] = args.model
    if args.max_chunks:
        config["teacher"]["strategy"]["max_chunks"] = args.max_chunks

    distiller = KnowledgeDistiller()

    if args.placeholder:
        distiller.save_placeholder(args.output)
        return

    if args.generate or config["teacher"]["type"] != "opencode":
        print("[Distiller] Caricamento chunk dalla Knowledge Base...")
        max_chunks = config["teacher"]["strategy"].get("max_chunks", 0)
        chunks = load_chunks(max_chunks=max_chunks)
        print(f"[Distiller] {len(chunks)} chunk caricati")
        distiller.generate_dataset_file(chunks, args.output)
    else:
        print("=" * 60)
        print("  KNOWLEDGE DISTILLER — Teacher: OpenCode")
        print("=" * 60)
        print()
        print("  Il Teacher predefinito è 'opencode' (l'assistente OpenCode).")
        print("  Per generare il dataset, l'assistente deve eseguire:")
        print()
        print("    python pipeline/knowledge_distiller.py --generate")
        print()
        print("  Oppure usa un Teacher automatico:")
        print("    python pipeline/knowledge_distiller.py --teacher groq")
        print(
            "    python pipeline/knowledge_distiller.py --teacher openrouter --model qwen/qwen3-32b"
        )
        print("    python pipeline/knowledge_distiller.py --teacher ollama")
        print()
        print("  Per un dataset di prova (1 esempio):")
        print("    python pipeline/knowledge_distiller.py --placeholder")
        print("=" * 60)


if __name__ == "__main__":
    main()
