import os
import sys
import subprocess
import json
import time
import logging
import signal
from pathlib import Path

logger = logging.getLogger("NanoGPTTrainer")
logging.basicConfig(level=logging.INFO)

NANOGPT_URL = "https://github.com/karpathy/nanoGPT.git"
NANOGPT_DIR = Path("external/nanoGPT")
DEFAULT_DATA_DIR = Path("data/nanogpt_c64")
DEFAULT_OUTPUT_DIR = Path("data/models/nanogpt")

CONFIG_TEMPLATE = """# Config for C64 nanoGPT training
# auto-generated by C64-LLM nanogpt_trainer.py

out_dir = '{out_dir}'
eval_interval = 200
log_interval = 10
eval_iters = 100
eval_only = False
always_save_checkpoint = True
init_from = '{init_from}'

# data
dataset = 'c64'
gradient_accumulation_steps = {grad_accum}
batch_size = {batch_size}
block_size = {block_size}

# model
n_layer = {n_layer}
n_head = {n_head}
n_embd = {n_embd}
dropout = 0.1
bias = False

# optimizer
learning_rate = {lr}
max_iters = {max_iters}
lr_decay_iters = {max_iters}
min_lr = {lr_min}
warmup_iters = {warmup_iters}
weight_decay = 1e-1
beta2 = 0.95
grad_clip = 1.0

# system
device = '{device}'
compile = {compile}
dtype = '{dtype}'
"""


class NanoGPTTrainer:
    def __init__(self, data_dir=None, output_dir=None, nano_repo=None):
        self.data_dir = Path(data_dir or DEFAULT_DATA_DIR)
        self.output_dir = Path(output_dir or DEFAULT_OUTPUT_DIR)
        self.nano_repo = Path(nano_repo or NANOGPT_DIR)
        self.proc = None
        self._running = False
        self._cancelled = False

    def ensure_repo(self):
        if self.nano_repo.exists() and (self.nano_repo / "train.py").exists():
            logger.info("nanoGPT gia presente in %s", self.nano_repo)
            return True
        logger.info("Clonazione nanoGPT in %s ...", self.nano_repo)
        self.nano_repo.parent.mkdir(parents=True, exist_ok=True)
        try:
            subprocess.run(
                ["git", "clone", NANOGPT_URL, str(self.nano_repo)],
                check=True, capture_output=True, text=True
            )
            logger.info("Clonazione completata")
            return True
        except subprocess.CalledProcessError as e:
            logger.error("Errore clonazione: %s", e.stderr)
            return False

    def link_data(self):
        target = self.nano_repo / "data" / "c64"
        target.mkdir(parents=True, exist_ok=True)
        for f in ["train.bin", "val.bin"]:
            src = self.data_dir / f
            if src.exists():
                dst = target / f
                if not dst.exists():
                    os.symlink(os.path.abspath(src), dst)
                    logger.info("Link: %s -> %s", dst, src)
        meta_src = self.data_dir / "meta.pkl"
        meta_dst = target / "meta.pkl"
        if meta_src.exists() and not meta_dst.exists():
            os.symlink(os.path.abspath(meta_src), meta_dst)

    def write_config(
        self,
        model_size="124M",
        init_from="scratch",
        batch_size=12,
        block_size=1024,
        lr=6e-4,
        max_iters=10000,
        device="cuda" if os.path.exists("/usr/local/cuda") else "cpu",
        dtype="float16" if os.path.exists("/usr/local/cuda") else "bfloat16",
        compile=False,
    ):
        sizes = {
            "124M": {"n_layer": 12, "n_head": 12, "n_embd": 768},
            "350M": {"n_layer": 24, "n_head": 16, "n_embd": 1024},
        }
        arch = sizes.get(model_size, sizes["124M"])
        if init_from == "scratch":
            init_from_val = "scratch"
        else:
            init_from_val = init_from

        grad_accum = max(1, 64 // batch_size)
        warmup_iters = min(2000, max_iters // 10)

        cfg = CONFIG_TEMPLATE.format(
            out_dir=self.output_dir,
            init_from=init_from_val,
            grad_accum=grad_accum,
            batch_size=batch_size,
            block_size=block_size,
            n_layer=arch["n_layer"],
            n_head=arch["n_head"],
            n_embd=arch["n_embd"],
            lr=lr,
            max_iters=max_iters,
            lr_min=lr * 0.1,
            warmup_iters=warmup_iters,
            device=device,
            compile=str(compile).lower(),
            dtype=dtype,
        )

        self.output_dir.mkdir(parents=True, exist_ok=True)
        cfg_path = self.nano_repo / "config" / "train_c64.py"
        with open(cfg_path, "w") as f:
            f.write(cfg)
        logger.info("Config salvata: %s", cfg_path)
        return cfg

    def train(self, config="config/train_c64.py", capture_output=False):
        if self._running:
            logger.warning("Training gia in esecuzione")
            return False

        self._running = True
        self._cancelled = False

        env = os.environ.copy()
        env["PYTHONUNBUFFERED"] = "1"

        cmd = [
            sys.executable,
            "train.py",
            config,
        ]

        logger.info("Avvio training: %s", " ".join(cmd))
        stdout = subprocess.PIPE if capture_output else None
        stderr = subprocess.STDOUT if capture_output else None

        try:
            self.proc = subprocess.Popen(
                cmd,
                cwd=str(self.nano_repo),
                env=env,
                stdout=stdout,
                stderr=stderr,
                text=True,
                bufsize=1,
            )
            if capture_output:
                output, _ = self.proc.communicate()
                return output
            self.proc.wait()
            logger.info("Training completato con codice %d", self.proc.returncode)
            return self.proc.returncode == 0
        except Exception as e:
            logger.error("Errore training: %s", e)
            return False
        finally:
            self._running = False
            self.proc = None

    def stop(self):
        self._cancelled = True
        if self.proc and self.proc.poll() is None:
            self.proc.terminate()
            logger.info("Training terminato")

    def is_running(self):
        return self._running


def main():
    import argparse

    parser = argparse.ArgumentParser(description="NanoGPT Trainer per C64-LLM")
    parser.add_argument("--model-size", default="124M", choices=["124M", "350M"])
    parser.add_argument("--init-from", default="scratch", help="scratch, gpt2, gpt2-medium, ...")
    parser.add_argument("--batch-size", type=int, default=12)
    parser.add_argument("--block-size", type=int, default=1024)
    parser.add_argument("--lr", type=float, default=6e-4)
    parser.add_argument("--max-iters", type=int, default=10000)
    parser.add_argument("--output-dir", default=None)
    parser.add_argument("--data-dir", default=None)

    args = parser.parse_args()

    trainer = NanoGPTTrainer(
        data_dir=args.data_dir,
        output_dir=args.output_dir,
    )

    if not trainer.ensure_repo():
        sys.exit(1)

    trainer.link_data()

    trainer.write_config(
        model_size=args.model_size,
        init_from=args.init_from,
        batch_size=args.batch_size,
        block_size=args.block_size,
        lr=args.lr,
        max_iters=args.max_iters,
    )

    success = trainer.train(capture_output=True)
    if success:
        logger.info("Training completato con successo")
    else:
        logger.error("Training fallito")
        sys.exit(1)


if __name__ == "__main__":
    main()
